- hosts: master-public
  tasks:

  - name: Install ansible
    apt: name=ansible state=present force=yes
    sudo: yes

  - name: Clone/update the boot repo
    git: repo=https://github.com/tilius/amazon-scala-paas.git dest=/home/ubuntu/paas-repo

  - name: Disable host key checking
    file: src=/home/ubuntu/paas-repo/ansible.cfg dest=/home/ubuntu/.ansible.cfg

