- hosts: master-public
  tasks:

  - name: Install ansible
    apt: name=ansible state=present force=yes
    sudo: yes

  - name: Install git
    apt: name=git state=present force=yes
    sudo: yes
    
  - name: Install fail2ban
    apt: name=fail2ban state=present force=yes
    sudo: yes 

  - name: Disable host key checking
    command: creates=/home/ubuntu/.ansible.cfg cp /home/ubuntu/paas-repo/ansible.cfg /home/ubuntu/.ansible.cfg

  - name: Set up NAT for slave machines
    command: iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    sudo: yes

  - name: Install sbt
    apt: name=sbt state=present force=yes update_cache=yes
    sudo: yes

  - name: Install OpenJDK
    apt: name=openjdk-7-jdk state=present force=yes
    sudo: yes

  - name: Clone/update the repo
    git: repo=https://github.com/tilius/amazon-scala-paas.git dest=/home/ubuntu/paas-repo

  - name: Shutdown the web server
    command: killall -TERM java  
    ignore_errors: yes

  - name: Stage the project
    command: chdir=/home/ubuntu/paas-repo/ sbt stage

  - name: Run the project in background
    command: chdir=/home/ubuntu/paas-repo/ nohup ./target/universal/stage/bin/amazon-app-platform &

