- hosts: master-public
  tasks:

  - name: Install ansible
    apt: name=ansible state=present force=yes
    sudo: yes

  - name: Install git
    apt: name=git state=present force=yes
    sudo: yes

  - name: Install fortune
    apt: name=fortune state=present force=yes
    sudo: yes

  - name: Clone/update the boot repo
    git: repo=https://github.com/tilius/amazon-scala-paas.git dest=/home/ubuntu/paas-repo

  - name: Disable host key checking
    command: creates=/home/ubuntu/.ansible.cfg cp /home/ubuntu/paas-repo/ansible.cfg /home/ubuntu/.ansible.cfg

