- hosts: master-public
  tasks:

  - name: Install ansible
    apt: name=ansible state=present force=yes
    sudo: yes

  - name: Install git
    apt: name=git state=present force=yes
    sudo: yes
    
  - name: Install fail2ban
    apt: name=fail2ban state=present force=yes
    sudo: yes 

  - name: Download Play
    get_url: url=http://downloads.typesafe.com/play/2.2.6/play-2.2.6.zip dest=/home/ubuntu/play-2.2.6.zip

  - name: Unzip Play
    unarchive: src=/home/ubuntu/play-2.2.6.zip dest=/home/ubuntu/ copy=no

  - name: Clone/update the repo
    git: repo=https://github.com/tilius/amazon-scala-paas.git dest=/home/ubuntu/paas-repo

  - name: Disable host key checking
    command: creates=/home/ubuntu/.ansible.cfg cp /home/ubuntu/paas-repo/ansible.cfg /home/ubuntu/.ansible.cfg

