- hosts: all
  user: vagrant
  sudo: yes
  tasks:

  - name: Install git
    apt: name=git state=present force=yes
    sudo: yes

  - name: Clone/update the repo
    git: repo=https://github.com/tilius/amazon-scala-paas.git dest=/home/ubuntu/paas-repo
    sudo: yes
    sudo_user: ubuntu

  - name: Update apt source list
    shell: echo "deb http://dl.bintray.com/sbt/debian /" | 
        sudo tee -a /etc/apt/sources.list.d/sbt.list ~/.apt.sbt.updated creates=~/.apt.sbt.updated

  - name: Install sbt
    apt: name=sbt state=present force=yes update_cache=yes
    sudo: yes

  - name: Install OpenJDK
    apt: name=openjdk-7-jdk state=present force=yes
    sudo: yes
    
  - name: Create directory jars
    file: path=~/paas-repo/lib/ state=directory
    sudo: yes
    sudo_user: ubuntu
    
  - name: Launch the service
    shell: nohup sbt run 1>/dev/null 2>&1 &
    args:
        chdir: ~/paas-repo
    sudo: yes
    sudo_user: ubuntu
